### ISSUE TITLE
Latest NPM module is out of date

### ISSUE THREAD

**Issue by phillipdarley** [2fdevs/bower-videogular-dash#2]
https://www.npmjs.com/package/videogular v1.4.1 is the latest version and still uses the old dashjs 1.6.0 API syntax which fails e.g. `var context = new Dash.di.DashContext()`. Needs to be updated to have the latest src http://static.videogular.com/scripts/dash/latest/vg-dash.js.

Also noticed that the export in index.js is invalid. Needs to be`module.exports = 'com.2fdevs.videogular.plugins.dash';` as opposed to `module.exports = 'com.2fdevs.videogular';`

**Comment by Elecash** [comment]
Thanks for noticing this, I'll try to fix this ASAP.

**Comment by Elecash** [comment]
Fixed!

**Comment by phillipdarley** [comment]
Awesome work!

On Sun, Jun 19, 2016 at 5:35 PM, Raúl Jiménez notifications@github.com
wrote:

> Fixed!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/videogular/bower-videogular-dash/issues/2#issuecomment-226984001,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABNwsNgtgbg59agoXpRYRKDkiOSFpRt4ks5qNPE6gaJpZM4IZVfb
> .

## 

Cheers,
Phil
